baseURL: https://nikolauseckhard.at/draft
languageCode: en-us
title: Nikolaus Eckhard
theme: oliver
assetDir: content
taxonomies:
  tag: tags

menu:
  nav:
  - name: index
    url: projects/
    weight: 1
  - name: about
    url: about/
    weight: 2